### DATA CLEANING

 read in the csv files
 join - add the IMD decile to each row of the crime dataset

In [ ]:
# hashed out as no longer needed
#  import the crime data files first which are in github releases folder 
#import requests

#url = "https://github.com/AnupmaDS1/Xmus-Jaxon-Flaxon-Waxon/releases/download/v1.1-data/WYP2024_2025.zip"
#r = requests.get(url)

#print(r.status_code)
#print(r.headers.get("content-type"))

#with open("Crimedata", "wb") as f:
#    f.write(r.content)

In [ ]:
#check the filesize
#import os
#print(os.path.getsize("Crimedata.zip"))

In [ ]:

imd = pd.read_excel('Data/Raw/File_1_IoD2025_OIMD.csv')

In [2]:
# import libraries, read in the 2 main csv files, name them as crime and imd and merge on LSOA code

import pandas as pd
crime = pd.read_csv('../data/raw/crime/WYP2025.csv')

In [6]:
# read in the IMD files

imd1 = pd.read_csv('../data/raw/deprivation/File_1_IoD2025_IOMD.csv')
imd5 = pd.read_csv('../data/raw/deprivation/File_5_IoD2025_ScoresFIOD.csv')
imd8 = pd.read_csv('../data/raw/deprivation/File_08_IoD2025_underlyingindicators_income.csv')
imd9 = pd.read_csv('../data/raw/deprivation/File_9_IoD2025_TransformedDomainScores.csv')

In [9]:
#check data

# Shape: (rows, columns)
print(crime.shape)

# Column names
print(crime.columns.tolist())


# Data types of each column
print(crime.dtypes)

(298385, 10)
['Crime ID', 'Month', 'Reported by', 'Longitude', 'Latitude', 'Location', 'LSOA code', 'LSOA name', 'Crime type', 'Last outcome category']
Crime ID                     str
Month                        str
Reported by                  str
Longitude                float64
Latitude                 float64
Location                     str
LSOA code                    str
LSOA name                    str
Crime type                   str
Last outcome category        str
dtype: object

In [14]:
# First 10 rows
imd9.head(10)

,LSOA code (2021),LSOA name (2021),Local Authority District code (2024),Local Authority District name (2024),Income Score - exponentially transformed,Employment Score - exponentially transformed,Education Score - exponentially transformed,Health Score - exponentially transformed,Crime Score - exponentially transformed,Barriers Score - exponentially transformed,Living Environment Score - exponentially transformed
0,E01000001,City of London 001A,E09000001,City of London,0.017,0.032,0.001,0.440,0.039,3.273,89.930
1,E01000002,City of London 001B,E09000001,City of London,0.059,0.015,0.057,0.809,0.030,0.763,48.545
2,E01000003,City of London 001C,E09000001,City of London,6.652,5.075,2.471,11.040,4.791,2.376,44.308
3,E01000005,City of London 001E,E09000001,City of London,18.533,14.315,17.004,26.299,6.240,24.599,40.634
4,E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham,33.527,17.865,24.915,9.790,14.360,54.585,28.464
5,E01000007,Barking and Dagenham 015A,E09000002,Barking and Dagenham,53.791,32.779,15.572,27.011,53.356,54.384,21.185
6,E01000008,Barking and Dagenham 015B,E09000002,Barking and Dagenham,57.970,34.153,26.511,24.658,29.639,88.689,22.426
7,E01000009,Barking and Dagenham 016B,E09000002,Barking and Dagenham,41.304,30.436,37.146,22.648,52.902,55.694,52.039
8,E01000011,Barking and Dagenham 016C,E09000002,Barking and Dagenham,43.865,24.228,44.267,20.048,20.893,46.865,69.481
9,E01000012,Barking and Dagenham 015D,E09000002,Barking and Dagenham,55.281,31.424,27.335,13.317,24.917,83.808,26.045

In [16]:
# Quick structural summary: dtypes, non-null counts, memory usage
crime.info()

<class 'pandas.DataFrame'>
RangeIndex: 298385 entries, 0 to 298384
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Crime ID               270516 non-null  str
 1   Month                  298385 non-null  str
 2   Reported by            298385 non-null  str
 3   Longitude              298385 non-null  float64
 4   Latitude               298385 non-null  float64
 5   Location               298385 non-null  str
 6   LSOA code              298385 non-null  str
 7   LSOA name              298385 non-null  str
 8   Crime type             298385 non-null  str
 9   Last outcome category  270516 non-null  str
dtypes: float64(2), str(8)
memory usage: 74.7 MB

In [17]:
# Basic descriptive stats for numeric columns
crime.describe()

           Longitude       Latitude
count  298385.000000  298385.000000
mean       -1.644382      53.758574
std         0.166992       0.070022
min        -2.177666      52.586004
25%        -1.775779      53.705111
50%        -1.638997      53.776991
75%        -1.528125      53.807229
max        -1.207936      54.821894

In [19]:
#amend col names to remove spaces for each of the dfs

crime.columns = crime.columns.str.strip().str.replace(' ', '_').str.lower()
imd1.columns = imd1.columns.str.strip().str.replace(' ', '_').str.lower()
imd5.columns = imd5.columns.str.strip().str.replace(' ', '_').str.lower()
imd8.columns = imd8.columns.str.strip().str.replace(' ', '_').str.lower()
imd9.columns = imd9.columns.str.strip().str.replace(' ', '_').str.lower()

In [ ]:
# Column names remove spaces

print(crime.columns.tolist())
print(imd1.columns.tolist())
print(imd5.columns.tolist())
print(imd8.columns.tolist())
print(imd9.columns.tolist())

['crime_id', 'month', 'reported_by', 'longitude', 'latitude', 'location', 'lsoa_code', 'lsoa_name', 'crime_type', 'last_outcome_category']
['lsoa_code_(2021)', 'lsoa_name_(2021)', 'local_authority_district_code_(2024)', 'local_authority_district_name_(2024)', 'index_of_multiple_deprivation_(imd)_rank_(where_1_is_most_deprived)', 'index_of_multiple_deprivation_(imd)_decile_(where_1_is_most_deprived_10%_of_lsoa']
['lsoa_code_(2021)', 'lsoa_name_(2021)', 'local_authority_district_code_(2024)', 'local_authority_district_name_(2024)', 'index_of_multiple_deprivation_(imd)_score', 'income_score_(rate)', 'employment_score_(rate)', 'education,_skills_and_training_score', 'health_deprivation_and_disability_score', 'crime_score', 'barriers_to_housing_and_services_score', 'living_environment_score', 'income_deprivation_affecting_children_index_(idaci)_score_(rate)', 'income_deprivation_affecting_older_people_(idaopi)_score_(rate)', 'children_and_young_people_sub-domain_score', 'adult_skills_sub-domain_score', 'geographical_barriers_sub-domain_score', 'wider_barriers_sub-domain_score', 'indoors_sub-domain_score', 'outdoors_sub-domain_score']
['lsoa_code_(2021)', 'lsoa_name_(2021)', 'local_authority_district_code_(2024)', 'local_authority_district_name_(2024)', 'income_domain_numerator', 'income_deprivation_affecting_children_index_(idaci)_numerator', 'income_deprivation_affecting_older_people_index_(idaopi)_numerator']
['lsoa_code_(2021)', 'lsoa_name_(2021)', 'local_authority_district_code_(2024)', 'local_authority_district_name_(2024)', 'income_score_-_exponentially_transformed', 'employment_score_-_exponentially_transformed', 'education_score_-_exponentially_transformed', 'health_score_-_exponentially_transformed', 'crime_score_-_exponentially_transformed', 'barriers_score_-_exponentially_transformed', 'living_environment_score_-_exponentially_transformed']

In [ ]:
# sigh - remove the brackets in col names and replace with _ AND don't replace the last one
imd1.columns = (
    imd1.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_', regex=False)
    .str.replace('(', '', regex=False)    # opening bracket -> removed
    .str.replace(')', '', regex=False)    # closing bracket -> removed
)

print(imd1.columns.tolist())

['lsoa_code_2021', 'lsoa_name_2021', 'local_authority_district_code_2024', 'local_authority_district_name_2024', 'index_of_multiple_deprivation_imd_rank_where_1_is_most_deprived', 'index_of_multiple_deprivation_imd_decile_where_1_is_most_deprived_10%_of_lsoa']

In [28]:
# repeat this on other imd dataframes

imd5.columns = (
    imd5.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_', regex=False)
    .str.replace('(', '', regex=False)    # opening bracket -> removed
    .str.replace(')', '', regex=False)    # closing bracket -> removed
)

imd8.columns = (
    imd8.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_', regex=False)
    .str.replace('(', '', regex=False)    # opening bracket -> removed
    .str.replace(')', '', regex=False)    # closing bracket -> removed
)

imd9.columns = (
    imd9.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_', regex=False)
    .str.replace('(', '', regex=False)    # opening bracket -> removed
    .str.replace(')', '', regex=False)    # closing bracket -> removed
)

print(imd5.columns.tolist())
print(imd8.columns.tolist())
print(imd9.columns.tolist())

['lsoa_code_2021', 'lsoa_name_2021', 'local_authority_district_code_2024', 'local_authority_district_name_2024', 'index_of_multiple_deprivation_imd_score', 'income_score_rate', 'employment_score_rate', 'education,_skills_and_training_score', 'health_deprivation_and_disability_score', 'crime_score', 'barriers_to_housing_and_services_score', 'living_environment_score', 'income_deprivation_affecting_children_index_idaci_score_rate', 'income_deprivation_affecting_older_people_idaopi_score_rate', 'children_and_young_people_sub-domain_score', 'adult_skills_sub-domain_score', 'geographical_barriers_sub-domain_score', 'wider_barriers_sub-domain_score', 'indoors_sub-domain_score', 'outdoors_sub-domain_score']
['lsoa_code_2021', 'lsoa_name_2021', 'local_authority_district_code_2024', 'local_authority_district_name_2024', 'income_domain_numerator', 'income_deprivation_affecting_children_index_idaci_numerator', 'income_deprivation_affecting_older_people_index_idaopi_numerator']
['lsoa_code_2021', 'lsoa_name_2021', 'local_authority_district_code_2024', 'local_authority_district_name_2024', 'income_score_-_exponentially_transformed', 'employment_score_-_exponentially_transformed', 'education_score_-_exponentially_transformed', 'health_score_-_exponentially_transformed', 'crime_score_-_exponentially_transformed', 'barriers_score_-_exponentially_transformed', 'living_environment_score_-_exponentially_transformed']

In [29]:
crime.dtypes

crime_id                     str
month                        str
reported_by                  str
longitude                float64
latitude                 float64
location                     str
lsoa_code                    str
lsoa_name                    str
crime_type                   str
last_outcome_category        str
dtype: object

In [30]:
crime.head()

,crime_id,month,reported_by,longitude,latitude,location,lsoa_code,lsoa_name,crime_type,last_outcome_category
0,NaN,2025-01,West Yorkshire Police,-1.472961,53.599861,On or near Railway Walk,E01007439,Barnsley 001D,Anti-social behaviour,NaN
1,03b3bda6de7c51f6cd0820b7f998a1f878e7acbb6b18dd...,2025-01,West Yorkshire Police,-1.882755,53.924927,On or near Moorside Lane,E01010646,Bradford 001A,Burglary,Investigation complete; no suspect identified
2,6f9fe9a78c7ed106fadb658e4fd5313c1bb5bc5c8aa223...,2025-01,West Yorkshire Police,-1.878940,53.943744,On or near Cross End Fold,E01010646,Bradford 001A,Shoplifting,Investigation complete; no suspect identified
3,9cbc69a540485581b55d8d4723eb41b97d364bc98132d8...,2025-01,West Yorkshire Police,-1.872959,53.941733,On or near Cornerstones Close,E01010646,Bradford 001A,Vehicle crime,Investigation complete; no suspect identified
4,050a7cc33129f37f41cbbd38fe858e63e07dc239720be8...,2025-01,West Yorkshire Police,-1.883567,53.934131,On or near Cocking Lane,E01010646,Bradford 001A,Violence and sexual offences,Unable to prosecute suspect

In [31]:
#check how many blanks are in the outcome col 

print(crime['last_outcome_category'].isna().sum())
print((crime['last_outcome_category'].str.strip() == '').sum())

27869
0

In [ ]:
#9.3% is a moderate amount — not negligible, do i need to invlude this in the write up and justify?
pct_missing = 27869 / total_before * 100
print(f"{pct_missing:.1f}% of rows have missing outcome")

9.3% of rows have missing outcome

In [ ]:
# merge or join the files on lsoa code


merged = crime.merge(imd, left_on='LSOA code', right_on='LSOA code (2021)', how='left')